### ISSUE TITLE
Remove all references to slices

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3-automation#19]
Remove support for legacy "slice:" terminology

**Comment by roleyfoley** [comment]
@ml019 Is there anymore work for this? I haven't heard of slices, so I'm taking that as a no.

**Comment by ml019** [comment]
Slice was the previous name for deployment unit - before your time. There were a couple of scripts that had a ```-s``` option to which -u was added but the legacy switch left behind. I think it is safe to close as you have done.
