### ISSUE TITLE
Make manageImages a separate build step

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3-automation#20]
At present, all the build scripts call manageImages.sh directly. In order to permit multiple builds per build job, for instance a node build as well as a swagger build, manageImages.sh needs to be made its own job step and explicitly included into the definition of any build jobs.

Since this will break existing job definitions, it will need to be included int he next breaking change.

**Comment by roleyfoley** [comment]
@ml019 Confirming that this is done?

**Comment by ml019** [comment]
Yep - closing.
